  spring:
    datasource:
      driverClassName: org.h2.Driver
      password: sa
      url: jdbc:h2:mem:test
      username: sa
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          web-allow-others: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    sql:
      init:
        platform: h2
        mode: always
        schema-locations: classpath:/2.sql
        data-locations: classpath:/1.sql
